### ISSUE TITLE
Expand world name character limit to more than 16 characters

### ISSUE THREAD

**Issue by terbin** [Avanatiker/WorldTools#20]
**As a** Minecraft player using the World Tools mod,

**I want** to be able to name my world downloads with more than 16 characters,

**So that** I can use more descriptive and meaningful names for my worlds, making them easier to identify and organize.

**Acceptance Criteria:**
- **Increase Character Limit**: The character limit for world download names within the World Tools mod is increased from 16 to at least 32 characters, allowing for more detailed naming.
- **UI Adaptation:** The user interface of the World Tools mod is adapted to accommodate longer world names without disrupting the layout or usability.

**Comment by rfresh2** [comment]
Done in https://github.com/Avanatiker/WorldTools/commit/f093720828dc69a2d1f71b6334719bf1d4aaadc4

I didn't adjust the text entry box width. it's a bit small because it'd otherwise get cut off on small screen sizes / large UI scalings.

It should be possible to calculate a larger width based on the current screen size but I think its fine for now. It doesn't even start scrolling text until i get to like 50 characters.

A larger UI overhaul like how the WorldDownloader mod showed a list of previous downloads and previews is planned, but that's a feature for another day.
